language: node_js
node_js: stable
sudo: required
dist: trusty
install:
  - npm cache verify
  - npm install
stages:
  - test
  - name: deploy
    if: branch = develop
jobs:
  include:
    - stage: test
      script: 
      - npm run test:unit
    - stage: deploy
      script:
      - npm run build
      - node upload.js